import type { Camp } from '@/types/database';

/**
 * Real camp data from Austin Summer Camps 2026 spreadsheet.
 * 64 camps across 10 categories.
 */
export const SAMPLE_CAMP_DATA: Camp[] = [
  {
    id: '1', name: "ATX Kids Club", slug: 'atx-kids-club',
    category: 'multi_activity', description: null, ages_min: 4, ages_max: 13,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "3005 S. Lamar Ste. D-109 #371", address: "3005 S. Lamar Ste. D-109 #371",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 135, price_max: 500, price_note: "sliding scale",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://atxkidsclub.org", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Sliding scale; public transit field trips",
    tags: ["field trips"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '2', name: "Austin Rising School", slug: 'austin-rising-school',
    category: 'multi_activity', description: null, ages_min: 6, ages_max: 15,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "6211 Parkwood Dr.", address: "6211 Parkwood Dr.",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 85, price_max: 400, price_note: "$400/wk or $85/day",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://austinrisingschool.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Themed weeks (HP, D&D, Forts)",
    tags: [],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '3', name: "Austin YMCA Full-Day Camps", slug: 'austin-ymca-full-day-camps',
    category: 'multi_activity', description: null, ages_min: 4, ages_max: 12,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Multiple YMCA locations", address: "Multiple YMCA locations",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 272, price_max: 365, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://austinymca.org/camp", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Scholarships available; pool daily at Y centers",
    tags: ["scholarships","swimming"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '4', name: "Austin YMCA Half-Day Camps", slug: 'austin-ymca-half-day-camps',
    category: 'multi_activity', description: null, ages_min: 3, ages_max: 12,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Multiple YMCA locations", address: "Multiple YMCA locations",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 145, price_max: 170, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://austinymca.org/camp", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Morning & afternoon options; preschool/sports/gym/swim",
    tags: ["swimming"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '5', name: "Austin Zoo Summer Camps", slug: 'austin-zoo-summer-camps',
    category: 'multi_activity', description: null, ages_min: 6, ages_max: 12,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "10808 Rawhide Trl.", address: "10808 Rawhide Trl.",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 395, price_max: 425, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://austinzoo.org", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Max 20 campers; zoo tours & animal encounters",
    tags: [],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '6', name: "Bricks & Minifigs South Austin", slug: 'bricks-minifigs-south-austin',
    category: 'multi_activity', description: null, ages_min: 7, ages_max: 14,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "5207 Brodie Ln. #130", address: "5207 Brodie Ln. #130",
    city: "Sunset Valley", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 50, price_max: 250, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'south_suburbs',
    website: "https://bricksandminifigs.com/southaustin-tx", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "LEGO building; kids take builds home",
    tags: [],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '7', name: "Camp Balcones (Camp Fire)", slug: 'camp-balcones-camp-fire',
    category: 'multi_activity', description: null, ages_min: 6, ages_max: 14,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Emma Long Metropolitan Park, 1600 City Park Rd.", address: "Emma Long Metropolitan Park, 1600 City Park Rd.",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 375, price_max: 450, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://camp-fire.org", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Nature-based; STEAM; transportation available",
    tags: ["transportation"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '8', name: "Camp Doublecreek", slug: 'camp-doublecreek',
    category: 'multi_activity', description: null, ages_min: 4, ages_max: 14,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Multiple pickup locations", address: "Multiple pickup locations",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 550, price_max: 550, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://campdoublecreek.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "50+ yrs; 8 bus pickup spots; horseback option",
    tags: ["transportation"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '9', name: "Camp Half-Blood Austin", slug: 'camp-half-blood-austin',
    category: 'multi_activity', description: null, ages_min: 9, ages_max: 18,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "McKinney Falls State Park Dining Hall", address: "McKinney Falls State Park Dining Hall",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 747, price_max: 747, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://camphalfbloodaustin.org", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Percy Jackson themed; scholarships available",
    tags: ["scholarships"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '10', name: "Camp Hope Day Camp", slug: 'camp-hope-day-camp',
    category: 'multi_activity', description: null, ages_min: 6, ages_max: 12,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "9508 Great Hills Trl.", address: "9508 Great Hills Trl.",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 195, price_max: 250, price_note: "Early bird pricing available",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://tllc.org/camp", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Bible-based; STEM, drama, music",
    tags: [],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '11', name: "Camp Vamonos!", slug: 'camp-vamonos',
    category: 'multi_activity', description: null, ages_min: 5, ages_max: 11,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "6919 Reese Ln.", address: "6919 Reese Ln.",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 250, price_max: 250, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://campvamonos.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Bilingual; backyard + daily outings",
    tags: ["bilingual"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '12', name: "Country Home Learning Center", slug: 'country-home-learning-center',
    category: 'multi_activity', description: null, ages_min: 5, ages_max: 13,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "NW & SW Austin locations", address: "NW & SW Austin locations",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 315, price_max: 315, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://countryhomelearningcenter.com/summer-camp", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Field trips, swim, reading program",
    tags: ["swimming","field trips"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '13', name: "Creative Action Summer Camp", slug: 'creative-action-summer-camp',
    category: 'multi_activity', description: null, ages_min: 5, ages_max: 11,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Multiple school campuses", address: "Multiple school campuses",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 395, price_max: 425, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://creativeaction.org", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Arts-based; professional teaching artists",
    tags: [],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '14', name: "Dragon's Lair Comic & Fantasy", slug: 'dragons-lair-comic-fantasy',
    category: 'multi_activity', description: null, ages_min: 7, ages_max: 17,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "2438 W. Anderson Ste. B-1", address: "2438 W. Anderson Ste. B-1",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 500, price_max: 600, price_note: "per week",
    camp_type: 'both', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://dlair.net/austin/events", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "D&D, Pokemon, How to Make Comics, MTG; aftercare; overnight option",
    tags: ["aftercare"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '15', name: "Earth Native Wilderness School (Day)", slug: 'earth-native-wilderness-school-day',
    category: 'nature_outdoor', description: null, ages_min: 4, ages_max: 12,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Multiple locations", address: "Multiple locations",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 235, price_max: 475, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://earthnativeschool.com/summer-camps", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Scholarships; aftercare; Nature Quest/Bushcraft/Forest Explorers",
    tags: ["scholarships","aftercare","transportation","nature","outdoor"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '16', name: "Fantastic Magic Camp", slug: 'fantastic-magic-camp',
    category: 'multi_activity', description: null, ages_min: 5, ages_max: 12,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Crestview (N Central) & Pflugerville ISD (Mt Playmore)", address: "Crestview (N Central) & Pflugerville ISD (Mt Playmore)",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 450, price_max: 450, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'north_suburbs',
    website: "https://magiccamp.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "10% sibling discount; scholarships; 9am-4pm + optional 4-6pm rehearsal",
    tags: ["scholarships","sibling discount"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '17', name: "Kidventure Day Camps", slug: 'kidventure-day-camps',
    category: 'multi_activity', description: null, ages_min: 3, ages_max: 14,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Westlake, Round Rock, Steiner Ranch, Lakeway, Rough Hollow, Sweetwater, Hamilton Pool Rd.", address: "Westlake, Round Rock, Steiner Ranch, Lakeway, Rough Hollow, Sweetwater, Hamilton Pool Rd.",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 370, price_max: 370, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://kidventure.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "30+ yrs; all-adult staff; 'Game On!' 2026 theme",
    tags: [],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '18', name: "Neuron Garage", slug: 'neuron-garage',
    category: 'multi_activity', description: null, ages_min: 5, ages_max: 12,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "N, Central, S Austin, Westlake", address: "N, Central, S Austin, Westlake",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 395, price_max: 455, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://neurongarage.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Growth mindset; recycled materials engineering",
    tags: [],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '19', name: "Steve & Kate's Camp", slug: 'steve-kates-camp',
    category: 'multi_activity', description: null, ages_min: 5, ages_max: 17,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Multiple Austin locations", address: "Multiple Austin locations",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: null, price_max: null, price_note: "Varies",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://steveandkates.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Kid-directed; choose own activities",
    tags: [],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '20', name: "Club SciKidz", slug: 'club-scikidz',
    category: 'academic_stem', description: null, ages_min: 4, ages_max: 15,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Multiple locations", address: "Multiple locations",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 425, price_max: 515, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://austin.clubscikidz.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "70+ themed camps; scholarships; aftercare",
    tags: ["scholarships","aftercare","STEM"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '21', name: "Girlstart STEM Camps", slug: 'girlstart-stem-camps',
    category: 'academic_stem', description: null, ages_min: 9, ages_max: 13,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "1400 W. Anderson Ln.", address: "1400 W. Anderson Ln.",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 450, price_max: 450, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://girlstart.org", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "$55 early bird discount thru Feb 28; nationally recognized",
    tags: ["early bird","STEM"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '22', name: "Idea Lab STEM Camps", slug: 'idea-lab-stem-camps',
    category: 'academic_stem', description: null, ages_min: 5, ages_max: 12,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "8620 Burnet Rd. / 13642 Research Blvd. / 7817 LaCrosse Ave. / Magellan International School", address: "8620 Burnet Rd. / 13642 Research Blvd. / 7817 LaCrosse Ave. / Magellan International School",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 415, price_max: 445, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://idealabkids.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "15% off NW/Circle C thru 3/31; 10% off Central thru 3/31",
    tags: ["STEM"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '23', name: "Mad Science Camps", slug: 'mad-science-camps',
    category: 'academic_stem', description: null, ages_min: 5, ages_max: 12,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Multiple locations", address: "Multiple locations",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 240, price_max: 420, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://austin.madscience.org", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Register now, pay later; 12 themes (robots, rockets, Spy Academy, etc.)",
    tags: ["STEM","robotics"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '24', name: "Lavner Education", slug: 'lavner-education',
    category: 'academic_stem', description: null, ages_min: 6, ages_max: 14,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "St. Edward's University; Magellan International School", address: "St. Edward's University; Magellan International School",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 599, price_max: 599, price_note: "Discounts available",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://lavnereducation.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Coding, Minecraft, AI, Robotics, Game Design",
    tags: ["STEM","coding","robotics"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '25', name: "Creator Camp", slug: 'creator-camp',
    category: 'academic_stem', description: null, ages_min: 5, ages_max: 13,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Cedar Park Exchange ATX / Bridgeland Church Round Rock / Glad Tidings / Austin Gateway S / Lake Travis Methodist Lakeway", address: "Cedar Park Exchange ATX / Bridgeland Church Round Rock / Glad Tidings / Austin Gateway S / Lake Travis Methodist Lakeway",
    city: "Cedar Park", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 170, price_max: 275, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'north_suburbs',
    website: "https://creatorcamp.org", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Animation, filmmaking, music production, entrepreneurship; Shark Tank featured",
    tags: ["STEM"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '26', name: "Thinkery Camp", slug: 'thinkery-camp',
    category: 'academic_stem', description: null, ages_min: 5, ages_max: 8,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "1830 Simond Ave.", address: "1830 Simond Ave.",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 385, price_max: 425, price_note: "Member/Standard pricing",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://thinkeryaustin.org/camp", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "STEAM; 5 rotating themes: Nature, Art, Maker, Storytelling, Community",
    tags: ["STEM"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '27', name: "UT Austin WiSTEM Camps", slug: 'ut-austin-wistem-camps',
    category: 'academic_stem', description: null, ages_min: 14, ages_max: 16,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "UT Austin campus", address: "UT Austin campus",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 200, price_max: 200, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://womeninstem.utexas.edu/high-school-camps", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "CEO Day Camps on-campus; virtual SEE & SLA academies; registration thru 5/1/26",
    tags: ["STEM"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '28', name: "KidStrong (multiple locations)", slug: 'kidstrong-multiple-locations',
    category: 'academic_stem', description: null, ages_min: 4, ages_max: 11,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "South / North / Cedar Park / Pflugerville", address: "South / North / Cedar Park / Pflugerville",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 250, price_max: 300, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://kidstrong.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Physical + mental development camps",
    tags: ["STEM"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '29', name: "Longhorn Engineering (UT Austin)", slug: 'longhorn-engineering-ut-austin',
    category: 'academic_stem', description: null, ages_min: 14, ages_max: 18,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "UT Austin campus", address: "UT Austin campus",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: null, price_max: null, price_note: "Varies",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://engineering.utexas.edu", phone: null, email: null,
    registration_url: null, registration_status: 'opens_soon', registration_opens_date: null,
    fills_fast: false, notes: "Registration closes Feb 22 — urgent!",
    tags: ["STEM"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '30', name: "The Art Garage", slug: 'the-art-garage',
    category: 'arts_music', description: null, ages_min: 6, ages_max: 14,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Circle Drive (Oak Hill) / N Lamar (Brentwood) / Brodie Ln (S Austin)", address: "Circle Drive (Oak Hill) / N Lamar (Brentwood) / Brodie Ln (S Austin)",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 95, price_max: 409, price_note: "$409/wk or $95/day",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://theartgarageaustin.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "$25 off thru 3/31 w/ code 365Things; ceramics, glass fusion, painting, sculpture",
    tags: ["arts","visual arts"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '31', name: "Cordovan Art School", slug: 'cordovan-art-school',
    category: 'arts_music', description: null, ages_min: 5, ages_max: 17,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Georgetown location + others", address: "Georgetown location + others",
    city: "Georgetown", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: null, price_max: null, price_note: "Varies",
    camp_type: 'day', schedule_type: 'full_day', region: 'north_suburbs',
    website: "https://cordovanartschool.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "40+ themed camps; painting, drawing, mixed media",
    tags: ["arts","visual arts"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '32', name: "Create! Studio ATX", slug: 'create-studio-atx',
    category: 'arts_music', description: null, ages_min: 4, ages_max: 9,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Austin", address: "Austin",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: null, price_max: null, price_note: "Varies",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://createstudioatx.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Themed art weeks for young kids",
    tags: ["arts"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '33', name: "Cooking, Arts & Swim (Westlake Chinese Academy)", slug: 'cooking-arts-swim-westlake-chinese-academy',
    category: 'arts_music', description: null, ages_min: 4, ages_max: 12,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "6800 Spanish Oaks Club Blvd.", address: "6800 Spanish Oaks Club Blvd.",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 450, price_max: 450, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://westlakechineseacademy.org/camp", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Cooking + arts + creek swim daily; aftercare available",
    tags: ["aftercare","swimming","arts"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '34', name: "Dougherty Arts Center (City of Austin)", slug: 'dougherty-arts-center-city-of-austin',
    category: 'arts_music', description: null, ages_min: 5, ages_max: 17,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "1110 Barton Springs Rd.", address: "1110 Barton Springs Rd.",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: null, price_max: null, price_note: "City rates",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://austintexas.gov/department/summer-camps-0", phone: null, email: null,
    registration_url: null, registration_status: 'opens_soon', registration_opens_date: "2026-02-28",
    fills_fast: false, notes: "Painting, pottery, photography, animation, drama; registration opens 2/28 for residents",
    tags: ["arts","visual arts"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '35', name: "TexARTS", slug: 'texarts',
    category: 'performing_arts', description: null, ages_min: 5, ages_max: 17,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "1110 S RR 620", address: "1110 S RR 620",
    city: "Lakeway", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 285, price_max: 750, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://tex-arts.org", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "School of Rock musical theatre 2-week camp; various arts camps",
    tags: ["arts","music","theater"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '36', name: "Hello Dancer", slug: 'hello-dancer',
    category: 'performing_arts', description: null, ages_min: 14, ages_max: 18,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "4410 Burnet Rd.", address: "4410 Burnet Rd.",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 275, price_max: 325, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://hellodancer.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Dance intensive for teens",
    tags: ["arts","dance"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '37', name: "Trinity Episcopal - Musical Theatre", slug: 'trinity-episcopal-musical-theatre',
    category: 'performing_arts', description: null, ages_min: 6, ages_max: 15,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "3901 Bee Cave Rd.", address: "3901 Bee Cave Rd.",
    city: "West Lake Hills", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: null, price_max: null, price_note: "Varies",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://austintrinity.org/programs/summer", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "2-week Broadway-style camp; evening performance",
    tags: ["arts","theater"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '38', name: "Camp Trinity", slug: 'camp-trinity',
    category: 'performing_arts', description: null, ages_min: 5, ages_max: 13,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "3901 Bee Cave Rd.", address: "3901 Bee Cave Rd.",
    city: "West Lake Hills", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 275, price_max: 275, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://austintrinity.org/programs/summer", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Half-day sessions; arts, sciences, athletics; teacher-led",
    tags: ["arts"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '39', name: "Austin Youth Fitness", slug: 'austin-youth-fitness',
    category: 'sports', description: null, ages_min: 4, ages_max: 11,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Pease Park", address: "Pease Park",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 325, price_max: 600, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://austinyouthfitness.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Multi-sport fitness camps",
    tags: ["sports"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '40', name: "Capital Gymnastics (Round Rock / Pflugerville)", slug: 'capital-gymnastics-round-rock-pflugerville',
    category: 'sports', description: null, ages_min: 4, ages_max: 12,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Round Rock & Pflugerville locations", address: "Round Rock & Pflugerville locations",
    city: "Round Rock", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 60, price_max: 60, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'north_suburbs',
    website: "https://capitalgymnastics.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Drop-in daily gymnastics camps",
    tags: ["sports","gymnastics"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '41', name: "Camp Jump! at Jump Gymnastics", slug: 'camp-jump-at-jump-gymnastics',
    category: 'sports', description: null, ages_min: 3, ages_max: 10,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "S Central 6800 W Gate / N Central 2117 W Anderson / Domain 10910 Domain Dr. / Hutto 571 Ed Schmidt Blvd.", address: "S Central 6800 W Gate / N Central 2117 W Anderson / Domain 10910 Domain Dr. / Hutto 571 Ed Schmidt Blvd.",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 355, price_max: 545, price_note: "$355 half-day / $445 full-day / $545 extended day",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://jumpgymnastics.com/campjump", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "10% sibling discount; voted Austin Family Most Fun Camp 8x",
    tags: ["sibling discount","sports","gymnastics"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '42', name: "Texas Rowing Center (Elementary)", slug: 'texas-rowing-center-elementary',
    category: 'sports', description: null, ages_min: 7, ages_max: 10,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "1541 West Cesar Chavez", address: "1541 West Cesar Chavez",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 325, price_max: 325, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://texasrowingcenter.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Learn-to-row; fun water activities",
    tags: ["sports","rowing"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '43', name: "Texas Rowing Center (Middle School)", slug: 'texas-rowing-center-middle-school',
    category: 'sports', description: null, ages_min: 11, ages_max: 13,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "1541 West Cesar Chavez", address: "1541 West Cesar Chavez",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 400, price_max: 400, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://texasrowingcenter.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Competitive rowing intro",
    tags: ["sports","rowing"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '44', name: "Texas Rowing Center (High School)", slug: 'texas-rowing-center-high-school',
    category: 'sports', description: null, ages_min: 14, ages_max: 18,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "1541 West Cesar Chavez", address: "1541 West Cesar Chavez",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 475, price_max: 475, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://texasrowingcenter.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Advanced rowing/crew",
    tags: ["sports","rowing"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '45', name: "All-Star Sports Camp", slug: 'all-star-sports-camp',
    category: 'sports', description: null, ages_min: 5, ages_max: 12,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "SoccerZone S Austin 9501 Menchaca Rd. / SoccerZone Lakeline 920 Old Mill Rd. Cedar Park", address: "SoccerZone S Austin 9501 Menchaca Rd. / SoccerZone Lakeline 920 Old Mill Rd. Cedar Park",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 270, price_max: 420, price_note: "Half-day / Full-day options",
    camp_type: 'day', schedule_type: 'full_day', region: 'north_suburbs',
    website: "https://allstarsportscamp.org", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Multi-sport; lunch from local restaurants for full-day",
    tags: ["sports"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '46', name: "Austin Sports Academy Soccer", slug: 'austin-sports-academy-soccer',
    category: 'sports', description: null, ages_min: 5, ages_max: 17,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Austin Sports Academy", address: "Austin Sports Academy",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 245, price_max: 425, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://austinsportsacademy.com/summercamps", phone: null, email: null,
    registration_url: null, registration_status: 'opens_soon', registration_opens_date: "2026-04-01",
    fills_fast: false, notes: "Registration opens April 1; 4-day and 5-day options",
    tags: ["sports","soccer"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '47', name: "i9 Sports at Trinity Episcopal", slug: 'i9-sports-at-trinity-episcopal',
    category: 'sports', description: null, ages_min: 5, ages_max: 17,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "3901 Bee Cave Rd.", address: "3901 Bee Cave Rd.",
    city: "West Lake Hills", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: null, price_max: null, price_note: "Varies",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://austintrinity.org/programs/summer", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Sports-specific and multi-sport camps",
    tags: ["sports"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '48', name: "Maverick Horseback Riding", slug: 'maverick-horseback-riding',
    category: 'sports', description: null, ages_min: 5, ages_max: 17,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Lockhart, TX (south of Austin)", address: "Lockhart, TX (south of Austin)",
    city: "Lockhart", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 400, price_max: 400, price_note: "per week",
    camp_type: 'both', schedule_type: 'full_day', region: 'hill_country',
    website: "https://maverickhorsebackriding.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Day & overnight; 1.5-2 hrs mounted daily; arts, yoga, horse soccer",
    tags: ["sports","soccer","horseback riding"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '49', name: "Coyote Kids Nature Camp", slug: 'coyote-kids-nature-camp',
    category: 'nature_outdoor', description: null, ages_min: 5, ages_max: 11,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "1042 Event Center Dr.", address: "1042 Event Center Dr.",
    city: "Dripping Springs", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 300, price_max: 300, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'hill_country',
    website: "https://drippingspringsranchpark.com/coyote-kids-camp", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Conservation, biodynamics, food chains; Hill Country setting",
    tags: ["nature","outdoor"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '50', name: "Earth Native Overnight Camps", slug: 'earth-native-overnight-camps',
    category: 'overnight', description: null, ages_min: 9, ages_max: 16,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "137 Woodview Ln.", address: "137 Woodview Ln.",
    city: "Bastrop", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 895, price_max: 895, price_note: "per week",
    camp_type: 'overnight', schedule_type: 'full_day', region: 'hill_country',
    website: "https://earthnativeschool.com/summer-camps", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Fire-making, shelter, archery, paintball; tents under stars",
    tags: ["overnight","sleepaway"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '51', name: "City of Austin Parks - Summer Camp", slug: 'city-of-austin-parks-summer-camp',
    category: 'nature_outdoor', description: null, ages_min: 5, ages_max: 12,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Multiple rec centers citywide", address: "Multiple rec centers citywide",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: null, price_max: null, price_note: "City rates",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://austintexas.gov/department/summer-camps-0", phone: null, email: null,
    registration_url: null, registration_status: 'opens_soon', registration_opens_date: "2026-02-21",
    fills_fast: false, notes: "Nature & Science reg opens 2/21 (residents 10am); Cultural/Art opens 2/28; FREE playground program 6/8-7/31",
    tags: ["free","nature","outdoor"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '52', name: "City of Austin - FREE Summer Playgrounds", slug: 'city-of-austin-free-summer-playgrounds',
    category: 'nature_outdoor', description: null, ages_min: 5, ages_max: 12,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Garrison, Gillis, Govalle, Walnut Creek Parks", address: "Garrison, Gillis, Govalle, Walnut Creek Parks",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 0, price_max: 0, price_note: "FREE",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://austintexas.gov/department/summer-camps-0", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "No advance registration; sign up day-of; Mon-Fri 9am-5pm",
    tags: ["nature","outdoor"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '53', name: "Camp Lone Star", slug: 'camp-lone-star',
    category: 'faith_vbs', description: null, ages_min: 7, ages_max: 18,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "2016 Camp Lone Star Rd.", address: "2016 Camp Lone Star Rd.",
    city: "La Grange, TX", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 339, price_max: 1129, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'hill_country',
    website: "https://camplonestar.org", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Christ-centered; 80+ yrs; overnight; scholarships available",
    tags: ["scholarships","faith-based","church"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '54', name: "St. Andrew's Episcopal School Camps", slug: 'st-andrews-episcopal-school-camps',
    category: 'faith_vbs', description: null, ages_min: 5, ages_max: 17,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "St. Andrew's campus", address: "St. Andrew's campus",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: null, price_max: null, price_note: "Varies",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://standrews.org", phone: null, email: null,
    registration_url: null, registration_status: 'opens_soon', registration_opens_date: "2026-02-25",
    fills_fast: false, notes: "STEAM, art, sports, music, preschool-full day; reg opens 2/25",
    tags: ["faith-based"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '55', name: "St. Michael's Catholic Prep Camps", slug: 'st-michaels-catholic-prep-camps',
    category: 'faith_vbs', description: null, ages_min: 5, ages_max: 17,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "St. Michael's campus", address: "St. Michael's campus",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: null, price_max: null, price_note: "Varies",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://stmichaelsschool.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "STEAM, art, music, sports, preschool; 300+ students/summer; spots limited",
    tags: ["faith-based"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '56', name: "Creator Camp (Faith venue locations)", slug: 'creator-camp-faith-venue-locations',
    category: 'faith_vbs', description: null, ages_min: 5, ages_max: 13,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Churches in Cedar Park, Round Rock, Austin, Lakeway", address: "Churches in Cedar Park, Round Rock, Austin, Lakeway",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 170, price_max: 275, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://creatorcamp.org", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Tech-focused; held at church venues",
    tags: ["faith-based"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '57', name: "Camp Champions", slug: 'camp-champions',
    category: 'overnight', description: null, ages_min: 6, ages_max: 17,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "775 Camp Rd.", address: "775 Camp Rd.",
    city: "Marble Falls", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 2400, price_max: 4595, price_note: "per week",
    camp_type: 'overnight', schedule_type: 'full_day', region: 'hill_country',
    website: "https://campchampions.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Lake LBJ; 1-4 week sessions; developmental focus",
    tags: ["overnight","sleepaway"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '58', name: "Kidventure Overnight Camps", slug: 'kidventure-overnight-camps',
    category: 'overnight', description: null, ages_min: 8, ages_max: 16,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Rocksprings, TX (Hill Country)", address: "Rocksprings, TX (Hill Country)",
    city: "Rocksprings", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 1670, price_max: 2240, price_note: "per week",
    camp_type: 'overnight', schedule_type: 'full_day', region: 'hill_country',
    website: "https://kidventure.com", phone: null, email: null,
    registration_url: null, registration_status: 'opens_soon', registration_opens_date: "2026-02-15",
    fills_fast: false, notes: "Tech-free; round-trip transport from Austin included; Safari/Quest (8-12), Echo (13-16)",
    tags: ["free","overnight","sleepaway"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '59', name: "Dragon's Lair Overnight Option", slug: 'dragons-lair-overnight-option',
    category: 'overnight', description: null, ages_min: 7, ages_max: 17,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "2438 W. Anderson Ste. B-1", address: "2438 W. Anderson Ste. B-1",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 500, price_max: 600, price_note: "per week",
    camp_type: 'overnight', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://dlair.net/austin/events", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Tabletop gaming overnight; limited details online",
    tags: ["overnight","sleepaway"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '60', name: "Badgerdog Creative Writing", slug: 'badgerdog-creative-writing',
    category: 'academic_writing', description: null, ages_min: 8, ages_max: 17,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Various Austin & Round Rock locations", address: "Various Austin & Round Rock locations",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 250, price_max: 595, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'north_suburbs',
    website: "https://austinlibrary.org/badgerdog", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "5% sibling discount; scholarships; student anthology published",
    tags: ["scholarships","sibling discount","academic"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '61', name: "Badgerdog at Trinity Episcopal", slug: 'badgerdog-at-trinity-episcopal',
    category: 'academic_writing', description: null, ages_min: 8, ages_max: 13,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "3901 Bee Cave Rd.", address: "3901 Bee Cave Rd.",
    city: "West Lake Hills", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: null, price_max: null, price_note: "Varies",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://austintrinity.org/programs/summer", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Poetry, fiction, nonfiction, playwriting with professional writers",
    tags: ["academic","writing"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '62', name: "Extend-A-Care for Kids", slug: 'extend-a-care-for-kids',
    category: 'special_needs', description: null, ages_min: 5, ages_max: 12,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "8-10 summer camp locations; office 55 N. IH 35", address: "8-10 summer camp locations; office 55 N. IH 35",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: 190, price_max: 190, price_note: "per week",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://eackids.org", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Field trips, swim, sports, STEM; financial assistance; 1:17-1:12 ratio",
    tags: ["swimming","field trips","inclusive","special needs"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '63', name: "City of Austin Therapeutic Recreation (McBeth)", slug: 'city-of-austin-therapeutic-recreation-mcbeth',
    category: 'special_needs', description: null, ages_min: 5, ages_max: 17,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "McBeth Recreation Center", address: "McBeth Recreation Center",
    city: "Austin", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: null, price_max: null, price_note: "City rates",
    camp_type: 'day', schedule_type: 'full_day', region: 'austin_metro',
    website: "https://austintexas.gov/department/summer-camps-0", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Registration opened 2/14 for residents",
    tags: ["inclusive","special needs"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: '64', name: "Echo Hill Ranch Gold Star Camp", slug: 'echo-hill-ranch-gold-star-camp',
    category: 'special_needs', description: null, ages_min: 6, ages_max: 17,
    duration: '1 week', days_of_week: ['Mon','Tue','Wed','Thu','Fri'],
    location_name: "Echo Hill Ranch", address: "Echo Hill Ranch",
    city: "Hill Country", state: 'TX', zip: null, latitude: null, longitude: null,
    price_min: null, price_max: null, price_note: "Varies / Subsidized",
    camp_type: 'day', schedule_type: 'full_day', region: 'hill_country',
    website: "https://echohillranch.com", phone: null, email: null,
    registration_url: null, registration_status: 'open', registration_opens_date: null,
    fills_fast: false, notes: "Founded by Kinky Friedman; Gold Star Children; free/low cost",
    tags: ["free","inclusive","special needs"],
    logo_url: null, image_url: null, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
];
