-- Austin Summer Camps 2026 - Seed Data
-- Generated from spreadsheet data
-- 64 camps

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('ATX Kids Club', 'atx-kids-club', 'multi_activity', 4, 13, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '3005 S. Lamar Ste. D-109 #371', '3005 S. Lamar Ste. D-109 #371', 'Austin', 'TX', 135, 500, 'sliding scale', 'day', 'full_day', 'austin_metro', 'https://atxkidsclub.org', 'open', NULL, false, 'Sliding scale; public transit field trips', ARRAY['field trips'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Austin Rising School', 'austin-rising-school', 'multi_activity', 6, 15, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '6211 Parkwood Dr.', '6211 Parkwood Dr.', 'Austin', 'TX', 85, 400, '$400/wk or $85/day', 'day', 'full_day', 'austin_metro', 'https://austinrisingschool.com', 'open', NULL, false, 'Themed weeks (HP, D&D, Forts)', NULL, true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Austin YMCA Full-Day Camps', 'austin-ymca-full-day-camps', 'multi_activity', 4, 12, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Multiple YMCA locations', 'Multiple YMCA locations', 'Austin', 'TX', 272, 365, 'per week', 'day', 'full_day', 'austin_metro', 'https://austinymca.org/camp', 'open', NULL, false, 'Scholarships available; pool daily at Y centers', ARRAY['scholarships','swimming'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Austin YMCA Half-Day Camps', 'austin-ymca-half-day-camps', 'multi_activity', 3, 12, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Multiple YMCA locations', 'Multiple YMCA locations', 'Austin', 'TX', 145, 170, 'per week', 'day', 'full_day', 'austin_metro', 'https://austinymca.org/camp', 'open', NULL, false, 'Morning & afternoon options; preschool/sports/gym/swim', ARRAY['swimming'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Austin Zoo Summer Camps', 'austin-zoo-summer-camps', 'multi_activity', 6, 12, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '10808 Rawhide Trl.', '10808 Rawhide Trl.', 'Austin', 'TX', 395, 425, 'per week', 'day', 'full_day', 'austin_metro', 'https://austinzoo.org', 'open', NULL, false, 'Max 20 campers; zoo tours & animal encounters', NULL, true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Bricks & Minifigs South Austin', 'bricks-minifigs-south-austin', 'multi_activity', 7, 14, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '5207 Brodie Ln. #130', '5207 Brodie Ln. #130', 'Sunset Valley', 'TX', 50, 250, 'per week', 'day', 'full_day', 'south_suburbs', 'https://bricksandminifigs.com/southaustin-tx', 'open', NULL, false, 'LEGO building; kids take builds home', NULL, true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Camp Balcones (Camp Fire)', 'camp-balcones-camp-fire', 'multi_activity', 6, 14, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Emma Long Metropolitan Park, 1600 City Park Rd.', 'Emma Long Metropolitan Park, 1600 City Park Rd.', 'Austin', 'TX', 375, 450, 'per week', 'day', 'full_day', 'austin_metro', 'https://camp-fire.org', 'open', NULL, false, 'Nature-based; STEAM; transportation available', ARRAY['transportation'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Camp Doublecreek', 'camp-doublecreek', 'multi_activity', 4, 14, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Multiple pickup locations', 'Multiple pickup locations', 'Austin', 'TX', 550, 550, 'per week', 'day', 'full_day', 'austin_metro', 'https://campdoublecreek.com', 'open', NULL, false, '50+ yrs; 8 bus pickup spots; horseback option', ARRAY['transportation'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Camp Half-Blood Austin', 'camp-half-blood-austin', 'multi_activity', 9, 18, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'McKinney Falls State Park Dining Hall', 'McKinney Falls State Park Dining Hall', 'Austin', 'TX', 747, 747, 'per week', 'day', 'full_day', 'austin_metro', 'https://camphalfbloodaustin.org', 'open', NULL, false, 'Percy Jackson themed; scholarships available', ARRAY['scholarships'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Camp Hope Day Camp', 'camp-hope-day-camp', 'multi_activity', 6, 12, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '9508 Great Hills Trl.', '9508 Great Hills Trl.', 'Austin', 'TX', 195, 250, 'Early bird pricing available', 'day', 'full_day', 'austin_metro', 'https://tllc.org/camp', 'open', NULL, false, 'Bible-based; STEM, drama, music', NULL, true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Camp Vamonos!', 'camp-vamonos', 'multi_activity', 5, 11, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '6919 Reese Ln.', '6919 Reese Ln.', 'Austin', 'TX', 250, 250, 'per week', 'day', 'full_day', 'austin_metro', 'https://campvamonos.com', 'open', NULL, false, 'Bilingual; backyard + daily outings', ARRAY['bilingual'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Country Home Learning Center', 'country-home-learning-center', 'multi_activity', 5, 13, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'NW & SW Austin locations', 'NW & SW Austin locations', 'Austin', 'TX', 315, 315, 'per week', 'day', 'full_day', 'austin_metro', 'https://countryhomelearningcenter.com/summer-camp', 'open', NULL, false, 'Field trips, swim, reading program', ARRAY['swimming','field trips'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Creative Action Summer Camp', 'creative-action-summer-camp', 'multi_activity', 5, 11, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Multiple school campuses', 'Multiple school campuses', 'Austin', 'TX', 395, 425, 'per week', 'day', 'full_day', 'austin_metro', 'https://creativeaction.org', 'open', NULL, false, 'Arts-based; professional teaching artists', NULL, true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Dragon''s Lair Comic & Fantasy', 'dragons-lair-comic-fantasy', 'multi_activity', 7, 17, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '2438 W. Anderson Ste. B-1', '2438 W. Anderson Ste. B-1', 'Austin', 'TX', 500, 600, 'per week', 'both', 'full_day', 'austin_metro', 'https://dlair.net/austin/events', 'open', NULL, false, 'D&D, Pokemon, How to Make Comics, MTG; aftercare; overnight option', ARRAY['aftercare'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Earth Native Wilderness School (Day)', 'earth-native-wilderness-school-day', 'nature_outdoor', 4, 12, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Multiple locations', 'Multiple locations', 'Austin', 'TX', 235, 475, 'per week', 'day', 'full_day', 'austin_metro', 'https://earthnativeschool.com/summer-camps', 'open', NULL, false, 'Scholarships; aftercare; Nature Quest/Bushcraft/Forest Explorers', ARRAY['scholarships','aftercare','transportation','nature','outdoor'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Fantastic Magic Camp', 'fantastic-magic-camp', 'multi_activity', 5, 12, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Crestview (N Central) & Pflugerville ISD (Mt Playmore)', 'Crestview (N Central) & Pflugerville ISD (Mt Playmore)', 'Austin', 'TX', 450, 450, 'per week', 'day', 'full_day', 'north_suburbs', 'https://magiccamp.com', 'open', NULL, false, '10% sibling discount; scholarships; 9am-4pm + optional 4-6pm rehearsal', ARRAY['scholarships','sibling discount'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Kidventure Day Camps', 'kidventure-day-camps', 'multi_activity', 3, 14, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Westlake, Round Rock, Steiner Ranch, Lakeway, Rough Hollow, Sweetwater, Hamilton Pool Rd.', 'Westlake, Round Rock, Steiner Ranch, Lakeway, Rough Hollow, Sweetwater, Hamilton Pool Rd.', 'Austin', 'TX', 370, 370, 'per week', 'day', 'full_day', 'austin_metro', 'https://kidventure.com', 'open', NULL, false, '30+ yrs; all-adult staff; ''Game On!'' 2026 theme', NULL, true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Neuron Garage', 'neuron-garage', 'multi_activity', 5, 12, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'N, Central, S Austin, Westlake', 'N, Central, S Austin, Westlake', 'Austin', 'TX', 395, 455, 'per week', 'day', 'full_day', 'austin_metro', 'https://neurongarage.com', 'open', NULL, false, 'Growth mindset; recycled materials engineering', NULL, true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Steve & Kate''s Camp', 'steve-kates-camp', 'multi_activity', 5, 17, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Multiple Austin locations', 'Multiple Austin locations', 'Austin', 'TX', NULL, NULL, 'Varies', 'day', 'full_day', 'austin_metro', 'https://steveandkates.com', 'open', NULL, false, 'Kid-directed; choose own activities', NULL, true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Club SciKidz', 'club-scikidz', 'academic_stem', 4, 15, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Multiple locations', 'Multiple locations', 'Austin', 'TX', 425, 515, 'per week', 'day', 'full_day', 'austin_metro', 'https://austin.clubscikidz.com', 'open', NULL, false, '70+ themed camps; scholarships; aftercare', ARRAY['scholarships','aftercare','STEM'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Girlstart STEM Camps', 'girlstart-stem-camps', 'academic_stem', 9, 13, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '1400 W. Anderson Ln.', '1400 W. Anderson Ln.', 'Austin', 'TX', 450, 450, 'per week', 'day', 'full_day', 'austin_metro', 'https://girlstart.org', 'open', NULL, false, '$55 early bird discount thru Feb 28; nationally recognized', ARRAY['early bird','STEM'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Idea Lab STEM Camps', 'idea-lab-stem-camps', 'academic_stem', 5, 12, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '8620 Burnet Rd. / 13642 Research Blvd. / 7817 LaCrosse Ave. / Magellan International School', '8620 Burnet Rd. / 13642 Research Blvd. / 7817 LaCrosse Ave. / Magellan International School', 'Austin', 'TX', 415, 445, 'per week', 'day', 'full_day', 'austin_metro', 'https://idealabkids.com', 'open', NULL, false, '15% off NW/Circle C thru 3/31; 10% off Central thru 3/31', ARRAY['STEM'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Mad Science Camps', 'mad-science-camps', 'academic_stem', 5, 12, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Multiple locations', 'Multiple locations', 'Austin', 'TX', 240, 420, 'per week', 'day', 'full_day', 'austin_metro', 'https://austin.madscience.org', 'open', NULL, false, 'Register now, pay later; 12 themes (robots, rockets, Spy Academy, etc.)', ARRAY['STEM','robotics'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Lavner Education', 'lavner-education', 'academic_stem', 6, 14, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'St. Edward''s University; Magellan International School', 'St. Edward''s University; Magellan International School', 'Austin', 'TX', 599, 599, 'Discounts available', 'day', 'full_day', 'austin_metro', 'https://lavnereducation.com', 'open', NULL, false, 'Coding, Minecraft, AI, Robotics, Game Design', ARRAY['STEM','coding','robotics'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Creator Camp', 'creator-camp', 'academic_stem', 5, 13, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Cedar Park Exchange ATX / Bridgeland Church Round Rock / Glad Tidings / Austin Gateway S / Lake Travis Methodist Lakeway', 'Cedar Park Exchange ATX / Bridgeland Church Round Rock / Glad Tidings / Austin Gateway S / Lake Travis Methodist Lakeway', 'Cedar Park', 'TX', 170, 275, 'per week', 'day', 'full_day', 'north_suburbs', 'https://creatorcamp.org', 'open', NULL, false, 'Animation, filmmaking, music production, entrepreneurship; Shark Tank featured', ARRAY['STEM'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Thinkery Camp', 'thinkery-camp', 'academic_stem', 5, 8, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '1830 Simond Ave.', '1830 Simond Ave.', 'Austin', 'TX', 385, 425, 'Member/Standard pricing', 'day', 'full_day', 'austin_metro', 'https://thinkeryaustin.org/camp', 'open', NULL, false, 'STEAM; 5 rotating themes: Nature, Art, Maker, Storytelling, Community', ARRAY['STEM'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('UT Austin WiSTEM Camps', 'ut-austin-wistem-camps', 'academic_stem', 14, 16, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'UT Austin campus', 'UT Austin campus', 'Austin', 'TX', 200, 200, 'per week', 'day', 'full_day', 'austin_metro', 'https://womeninstem.utexas.edu/high-school-camps', 'open', NULL, false, 'CEO Day Camps on-campus; virtual SEE & SLA academies; registration thru 5/1/26', ARRAY['STEM'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('KidStrong (multiple locations)', 'kidstrong-multiple-locations', 'academic_stem', 4, 11, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'South / North / Cedar Park / Pflugerville', 'South / North / Cedar Park / Pflugerville', 'Austin', 'TX', 250, 300, 'per week', 'day', 'full_day', 'austin_metro', 'https://kidstrong.com', 'open', NULL, false, 'Physical + mental development camps', ARRAY['STEM'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Longhorn Engineering (UT Austin)', 'longhorn-engineering-ut-austin', 'academic_stem', 14, 18, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'UT Austin campus', 'UT Austin campus', 'Austin', 'TX', NULL, NULL, 'Varies', 'day', 'full_day', 'austin_metro', 'https://engineering.utexas.edu', 'opens_soon', NULL, false, 'Registration closes Feb 22 — urgent!', ARRAY['STEM'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('The Art Garage', 'the-art-garage', 'arts_music', 6, 14, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Circle Drive (Oak Hill) / N Lamar (Brentwood) / Brodie Ln (S Austin)', 'Circle Drive (Oak Hill) / N Lamar (Brentwood) / Brodie Ln (S Austin)', 'Austin', 'TX', 95, 409, '$409/wk or $95/day', 'day', 'full_day', 'austin_metro', 'https://theartgarageaustin.com', 'open', NULL, false, '$25 off thru 3/31 w/ code 365Things; ceramics, glass fusion, painting, sculpture', ARRAY['arts','visual arts'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Cordovan Art School', 'cordovan-art-school', 'arts_music', 5, 17, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Georgetown location + others', 'Georgetown location + others', 'Georgetown', 'TX', NULL, NULL, 'Varies', 'day', 'full_day', 'north_suburbs', 'https://cordovanartschool.com', 'open', NULL, false, '40+ themed camps; painting, drawing, mixed media', ARRAY['arts','visual arts'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Create! Studio ATX', 'create-studio-atx', 'arts_music', 4, 9, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Austin', 'Austin', 'Austin', 'TX', NULL, NULL, 'Varies', 'day', 'full_day', 'austin_metro', 'https://createstudioatx.com', 'open', NULL, false, 'Themed art weeks for young kids', ARRAY['arts'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Cooking, Arts & Swim (Westlake Chinese Academy)', 'cooking-arts-swim-westlake-chinese-academy', 'arts_music', 4, 12, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '6800 Spanish Oaks Club Blvd.', '6800 Spanish Oaks Club Blvd.', 'Austin', 'TX', 450, 450, 'per week', 'day', 'full_day', 'austin_metro', 'https://westlakechineseacademy.org/camp', 'open', NULL, false, 'Cooking + arts + creek swim daily; aftercare available', ARRAY['aftercare','swimming','arts'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Dougherty Arts Center (City of Austin)', 'dougherty-arts-center-city-of-austin', 'arts_music', 5, 17, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '1110 Barton Springs Rd.', '1110 Barton Springs Rd.', 'Austin', 'TX', NULL, NULL, 'City rates', 'day', 'full_day', 'austin_metro', 'https://austintexas.gov/department/summer-camps-0', 'opens_soon', '2026-02-28', false, 'Painting, pottery, photography, animation, drama; registration opens 2/28 for residents', ARRAY['arts','visual arts'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('TexARTS', 'texarts', 'performing_arts', 5, 17, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '1110 S RR 620', '1110 S RR 620', 'Lakeway', 'TX', 285, 750, 'per week', 'day', 'full_day', 'austin_metro', 'https://tex-arts.org', 'open', NULL, false, 'School of Rock musical theatre 2-week camp; various arts camps', ARRAY['arts','music','theater'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Hello Dancer', 'hello-dancer', 'performing_arts', 14, 18, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '4410 Burnet Rd.', '4410 Burnet Rd.', 'Austin', 'TX', 275, 325, 'per week', 'day', 'full_day', 'austin_metro', 'https://hellodancer.com', 'open', NULL, false, 'Dance intensive for teens', ARRAY['arts','dance'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Trinity Episcopal - Musical Theatre', 'trinity-episcopal-musical-theatre', 'performing_arts', 6, 15, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '3901 Bee Cave Rd.', '3901 Bee Cave Rd.', 'West Lake Hills', 'TX', NULL, NULL, 'Varies', 'day', 'full_day', 'austin_metro', 'https://austintrinity.org/programs/summer', 'open', NULL, false, '2-week Broadway-style camp; evening performance', ARRAY['arts','theater'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Camp Trinity', 'camp-trinity', 'performing_arts', 5, 13, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '3901 Bee Cave Rd.', '3901 Bee Cave Rd.', 'West Lake Hills', 'TX', 275, 275, 'per week', 'day', 'full_day', 'austin_metro', 'https://austintrinity.org/programs/summer', 'open', NULL, false, 'Half-day sessions; arts, sciences, athletics; teacher-led', ARRAY['arts'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Austin Youth Fitness', 'austin-youth-fitness', 'sports', 4, 11, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Pease Park', 'Pease Park', 'Austin', 'TX', 325, 600, 'per week', 'day', 'full_day', 'austin_metro', 'https://austinyouthfitness.com', 'open', NULL, false, 'Multi-sport fitness camps', ARRAY['sports'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Capital Gymnastics (Round Rock / Pflugerville)', 'capital-gymnastics-round-rock-pflugerville', 'sports', 4, 12, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Round Rock & Pflugerville locations', 'Round Rock & Pflugerville locations', 'Round Rock', 'TX', 60, 60, 'per week', 'day', 'full_day', 'north_suburbs', 'https://capitalgymnastics.com', 'open', NULL, false, 'Drop-in daily gymnastics camps', ARRAY['sports','gymnastics'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Camp Jump! at Jump Gymnastics', 'camp-jump-at-jump-gymnastics', 'sports', 3, 10, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'S Central 6800 W Gate / N Central 2117 W Anderson / Domain 10910 Domain Dr. / Hutto 571 Ed Schmidt Blvd.', 'S Central 6800 W Gate / N Central 2117 W Anderson / Domain 10910 Domain Dr. / Hutto 571 Ed Schmidt Blvd.', 'Austin', 'TX', 355, 545, '$355 half-day / $445 full-day / $545 extended day', 'day', 'full_day', 'austin_metro', 'https://jumpgymnastics.com/campjump', 'open', NULL, false, '10% sibling discount; voted Austin Family Most Fun Camp 8x', ARRAY['sibling discount','sports','gymnastics'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Texas Rowing Center (Elementary)', 'texas-rowing-center-elementary', 'sports', 7, 10, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '1541 West Cesar Chavez', '1541 West Cesar Chavez', 'Austin', 'TX', 325, 325, 'per week', 'day', 'full_day', 'austin_metro', 'https://texasrowingcenter.com', 'open', NULL, false, 'Learn-to-row; fun water activities', ARRAY['sports','rowing'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Texas Rowing Center (Middle School)', 'texas-rowing-center-middle-school', 'sports', 11, 13, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '1541 West Cesar Chavez', '1541 West Cesar Chavez', 'Austin', 'TX', 400, 400, 'per week', 'day', 'full_day', 'austin_metro', 'https://texasrowingcenter.com', 'open', NULL, false, 'Competitive rowing intro', ARRAY['sports','rowing'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Texas Rowing Center (High School)', 'texas-rowing-center-high-school', 'sports', 14, 18, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '1541 West Cesar Chavez', '1541 West Cesar Chavez', 'Austin', 'TX', 475, 475, 'per week', 'day', 'full_day', 'austin_metro', 'https://texasrowingcenter.com', 'open', NULL, false, 'Advanced rowing/crew', ARRAY['sports','rowing'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('All-Star Sports Camp', 'all-star-sports-camp', 'sports', 5, 12, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'SoccerZone S Austin 9501 Menchaca Rd. / SoccerZone Lakeline 920 Old Mill Rd. Cedar Park', 'SoccerZone S Austin 9501 Menchaca Rd. / SoccerZone Lakeline 920 Old Mill Rd. Cedar Park', 'Austin', 'TX', 270, 420, 'Half-day / Full-day options', 'day', 'full_day', 'north_suburbs', 'https://allstarsportscamp.org', 'open', NULL, false, 'Multi-sport; lunch from local restaurants for full-day', ARRAY['sports'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Austin Sports Academy Soccer', 'austin-sports-academy-soccer', 'sports', 5, 17, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Austin Sports Academy', 'Austin Sports Academy', 'Austin', 'TX', 245, 425, 'per week', 'day', 'full_day', 'austin_metro', 'https://austinsportsacademy.com/summercamps', 'opens_soon', '2026-04-01', false, 'Registration opens April 1; 4-day and 5-day options', ARRAY['sports','soccer'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('i9 Sports at Trinity Episcopal', 'i9-sports-at-trinity-episcopal', 'sports', 5, 17, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '3901 Bee Cave Rd.', '3901 Bee Cave Rd.', 'West Lake Hills', 'TX', NULL, NULL, 'Varies', 'day', 'full_day', 'austin_metro', 'https://austintrinity.org/programs/summer', 'open', NULL, false, 'Sports-specific and multi-sport camps', ARRAY['sports'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Maverick Horseback Riding', 'maverick-horseback-riding', 'sports', 5, 17, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Lockhart, TX (south of Austin)', 'Lockhart, TX (south of Austin)', 'Lockhart', 'TX', 400, 400, 'per week', 'both', 'full_day', 'hill_country', 'https://maverickhorsebackriding.com', 'open', NULL, false, 'Day & overnight; 1.5-2 hrs mounted daily; arts, yoga, horse soccer', ARRAY['sports','soccer','horseback riding'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Coyote Kids Nature Camp', 'coyote-kids-nature-camp', 'nature_outdoor', 5, 11, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '1042 Event Center Dr.', '1042 Event Center Dr.', 'Dripping Springs', 'TX', 300, 300, 'per week', 'day', 'full_day', 'hill_country', 'https://drippingspringsranchpark.com/coyote-kids-camp', 'open', NULL, false, 'Conservation, biodynamics, food chains; Hill Country setting', ARRAY['nature','outdoor'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Earth Native Overnight Camps', 'earth-native-overnight-camps', 'overnight', 9, 16, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '137 Woodview Ln.', '137 Woodview Ln.', 'Bastrop', 'TX', 895, 895, 'per week', 'overnight', 'full_day', 'hill_country', 'https://earthnativeschool.com/summer-camps', 'open', NULL, false, 'Fire-making, shelter, archery, paintball; tents under stars', ARRAY['overnight','sleepaway'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('City of Austin Parks - Summer Camp', 'city-of-austin-parks-summer-camp', 'nature_outdoor', 5, 12, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Multiple rec centers citywide', 'Multiple rec centers citywide', 'Austin', 'TX', NULL, NULL, 'City rates', 'day', 'full_day', 'austin_metro', 'https://austintexas.gov/department/summer-camps-0', 'opens_soon', '2026-02-21', false, 'Nature & Science reg opens 2/21 (residents 10am); Cultural/Art opens 2/28; FREE playground program 6/8-7/31', ARRAY['free','nature','outdoor'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('City of Austin - FREE Summer Playgrounds', 'city-of-austin-free-summer-playgrounds', 'nature_outdoor', 5, 12, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Garrison, Gillis, Govalle, Walnut Creek Parks', 'Garrison, Gillis, Govalle, Walnut Creek Parks', 'Austin', 'TX', 0, 0, 'FREE', 'day', 'full_day', 'austin_metro', 'https://austintexas.gov/department/summer-camps-0', 'open', NULL, false, 'No advance registration; sign up day-of; Mon-Fri 9am-5pm', ARRAY['nature','outdoor'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Camp Lone Star', 'camp-lone-star', 'faith_vbs', 7, 18, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '2016 Camp Lone Star Rd.', '2016 Camp Lone Star Rd.', 'La Grange, TX', 'TX', 339, 1129, 'per week', 'day', 'full_day', 'hill_country', 'https://camplonestar.org', 'open', NULL, false, 'Christ-centered; 80+ yrs; overnight; scholarships available', ARRAY['scholarships','faith-based','church'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('St. Andrew''s Episcopal School Camps', 'st-andrews-episcopal-school-camps', 'faith_vbs', 5, 17, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'St. Andrew''s campus', 'St. Andrew''s campus', 'Austin', 'TX', NULL, NULL, 'Varies', 'day', 'full_day', 'austin_metro', 'https://standrews.org', 'opens_soon', '2026-02-25', false, 'STEAM, art, sports, music, preschool-full day; reg opens 2/25', ARRAY['faith-based'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('St. Michael''s Catholic Prep Camps', 'st-michaels-catholic-prep-camps', 'faith_vbs', 5, 17, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'St. Michael''s campus', 'St. Michael''s campus', 'Austin', 'TX', NULL, NULL, 'Varies', 'day', 'full_day', 'austin_metro', 'https://stmichaelsschool.com', 'open', NULL, false, 'STEAM, art, music, sports, preschool; 300+ students/summer; spots limited', ARRAY['faith-based'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Creator Camp (Faith venue locations)', 'creator-camp-faith-venue-locations', 'faith_vbs', 5, 13, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Churches in Cedar Park, Round Rock, Austin, Lakeway', 'Churches in Cedar Park, Round Rock, Austin, Lakeway', 'Austin', 'TX', 170, 275, 'per week', 'day', 'full_day', 'austin_metro', 'https://creatorcamp.org', 'open', NULL, false, 'Tech-focused; held at church venues', ARRAY['faith-based'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Camp Champions', 'camp-champions', 'overnight', 6, 17, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '775 Camp Rd.', '775 Camp Rd.', 'Marble Falls', 'TX', 2400, 4595, 'per week', 'overnight', 'full_day', 'hill_country', 'https://campchampions.com', 'open', NULL, false, 'Lake LBJ; 1-4 week sessions; developmental focus', ARRAY['overnight','sleepaway'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Kidventure Overnight Camps', 'kidventure-overnight-camps', 'overnight', 8, 16, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Rocksprings, TX (Hill Country)', 'Rocksprings, TX (Hill Country)', 'Rocksprings', 'TX', 1670, 2240, 'per week', 'overnight', 'full_day', 'hill_country', 'https://kidventure.com', 'opens_soon', '2026-02-15', false, 'Tech-free; round-trip transport from Austin included; Safari/Quest (8-12), Echo (13-16)', ARRAY['free','overnight','sleepaway'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Dragon''s Lair Overnight Option', 'dragons-lair-overnight-option', 'overnight', 7, 17, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '2438 W. Anderson Ste. B-1', '2438 W. Anderson Ste. B-1', 'Austin', 'TX', 500, 600, 'per week', 'overnight', 'full_day', 'austin_metro', 'https://dlair.net/austin/events', 'open', NULL, false, 'Tabletop gaming overnight; limited details online', ARRAY['overnight','sleepaway'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Badgerdog Creative Writing', 'badgerdog-creative-writing', 'academic_writing', 8, 17, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Various Austin & Round Rock locations', 'Various Austin & Round Rock locations', 'Austin', 'TX', 250, 595, 'per week', 'day', 'full_day', 'north_suburbs', 'https://austinlibrary.org/badgerdog', 'open', NULL, false, '5% sibling discount; scholarships; student anthology published', ARRAY['scholarships','sibling discount','academic'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Badgerdog at Trinity Episcopal', 'badgerdog-at-trinity-episcopal', 'academic_writing', 8, 13, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '3901 Bee Cave Rd.', '3901 Bee Cave Rd.', 'West Lake Hills', 'TX', NULL, NULL, 'Varies', 'day', 'full_day', 'austin_metro', 'https://austintrinity.org/programs/summer', 'open', NULL, false, 'Poetry, fiction, nonfiction, playwriting with professional writers', ARRAY['academic','writing'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Extend-A-Care for Kids', 'extend-a-care-for-kids', 'special_needs', 5, 12, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], '8-10 summer camp locations; office 55 N. IH 35', '8-10 summer camp locations; office 55 N. IH 35', 'Austin', 'TX', 190, 190, 'per week', 'day', 'full_day', 'austin_metro', 'https://eackids.org', 'open', NULL, false, 'Field trips, swim, sports, STEM; financial assistance; 1:17-1:12 ratio', ARRAY['swimming','field trips','inclusive','special needs'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('City of Austin Therapeutic Recreation (McBeth)', 'city-of-austin-therapeutic-recreation-mcbeth', 'special_needs', 5, 17, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'McBeth Recreation Center', 'McBeth Recreation Center', 'Austin', 'TX', NULL, NULL, 'City rates', 'day', 'full_day', 'austin_metro', 'https://austintexas.gov/department/summer-camps-0', 'open', NULL, false, 'Registration opened 2/14 for residents', ARRAY['inclusive','special needs'], true);

INSERT INTO camps (name, slug, category, ages_min, ages_max, duration, days_of_week, location_name, address, city, state, price_min, price_max, price_note, camp_type, schedule_type, region, website, registration_status, registration_opens_date, fills_fast, notes, tags, is_active)
VALUES ('Echo Hill Ranch Gold Star Camp', 'echo-hill-ranch-gold-star-camp', 'special_needs', 6, 17, '1 week', ARRAY['Mon','Tue','Wed','Thu','Fri'], 'Echo Hill Ranch', 'Echo Hill Ranch', 'Hill Country', 'TX', NULL, NULL, 'Varies / Subsidized', 'day', 'full_day', 'hill_country', 'https://echohillranch.com', 'open', NULL, false, 'Founded by Kinky Friedman; Gold Star Children; free/low cost', ARRAY['free','inclusive','special needs'], true);

